Repository reubeno/brush, pull requests merged in 2025-06, with the labels that each got.

#509 Allow reading a script from bytes
  brush-core/src/shell.rs
Labels: area: parsing

#446 feat(parser): add gettext enabled quotes
  brush-core/src/expansion.rs
  brush-interactive/src/reedline/highlighter.rs
  brush-parser/src/snapshots/brush_parser__word__tests__parse_ansi_c_quoted_text.snap
  brush-parser/src/snapshots/brush_parser__word__tests__parse_double_quoted_text.snap
  brush-parser/src/snapshots/brush_parser__word__tests__parse_gettext_double_quoted_text.snap
  brush-parser/src/word.rs
  brush-shell/tests/cases/word_expansion.yaml
Labels: area: parsing

#559 fix(traps): add stub definition for RETURN trap
  brush-core/src/sys/unix/signal.rs
  brush-core/src/traps.rs
Labels: origin: ble.sh usage

#560 fix(functions): allow func names to contain slashes
  brush-core/src/commands.rs
  brush-shell/tests/cases/functions.yaml
Labels: origin: ble.sh usage

#562 fix(arithmetic): correct left shift handling
  brush-parser/src/tokenizer.rs
  brush-shell/tests/cases/arithmetic.yaml
  brush-shell/tests/cases/here.yaml
Labels: area: parsing

#578 fix(for/case): allow reserved words in for word lists
  brush-parser/src/parser.rs
  brush-shell/tests/cases/compound_cmds/case.yaml
  brush-shell/tests/cases/compound_cmds/for.yaml
Labels: origin: user

#587 tests: add test cases for open issues
  brush-shell/tests/cases/builtins/unset.yaml
  brush-shell/tests/cases/here.yaml
Labels: area: testing
